// Regenerates THIRD_PARTY_NOTICES.md from the installed production dependency tree.
// Usage: npm run notices   (run after `npm ci`; dev-only tools are not redistributed and are omitted)
import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";

interface Pkg {
  name: string;
  version: string;
  license: string;
  repository: string;
  licenseText: string | null;
}

const dirs = execSync("npm ls --omit=dev --all --parseable", { encoding: "utf8" }).split("\n").filter(Boolean).slice(1);
const seen = new Map<string, Pkg>();
for (const dir of dirs) {
  const pj = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
  const key = `${pj.name}@${pj.version}`;
  if (seen.has(key)) continue;
  const license = typeof pj.license === "string" ? pj.license : JSON.stringify(pj.license ?? pj.licenses ?? "UNKNOWN");
  const repo = typeof pj.repository === "string" ? pj.repository : (pj.repository?.url ?? pj.homepage ?? "");
  const file = fs.readdirSync(dir).find((f) => /^(licen[cs]e|copying)(\.|$)/i.test(f));
  seen.set(key, {
    name: pj.name,
    version: pj.version,
    license,
    repository: String(repo).replace(/^git\+/, "").replace(/\.git$/, ""),
    licenseText: file ? fs.readFileSync(path.join(dir, file), "utf8").trim() : null,
  });
}
const pkgs = [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));

let out = `# Third-Party Notices

Jev Civilizations is licensed under the MIT License (see \`LICENSE\`). It depends on the open source packages
listed below, which are installed by npm and are **not** stored in this repository. Each is used under its own
license. This file is generated by \`npm run notices\` from the production dependency tree; development-only
tools (TypeScript, ESLint, Vitest, Playwright, tsx) are not redistributed and are omitted.

## Notes on specific licenses

- **caniuse-lite** (CC-BY-4.0): browser-support data © Alexis Deveria and contributors, used under the Creative
  Commons Attribution 4.0 International license (https://creativecommons.org/licenses/by/4.0/). It is a build-time
  dependency of Next.js.
- **@img/sharp-libvips-*** (LGPL-3.0-or-later): prebuilt libvips binaries that npm may install as an *optional*
  dependency of Next.js image optimization for your platform. This application does not use \`next/image\`. The
  binaries are unmodified and dynamically loaded; their source is available from https://github.com/lovell/sharp-libvips.
  If you redistribute an image or bundle that includes them (for example the provided Dockerfile's output), you must
  comply with the LGPL for those binaries.

## Package list (production dependencies)

| Package | Version | License | Source |
| --- | --- | --- | --- |
`;
for (const p of pkgs) out += `| ${p.name} | ${p.version} | ${p.license} | ${p.repository} |\n`;
out += `\n## License texts\n`;
const byText = new Map<string, string[]>();
for (const p of pkgs) {
  const t = p.licenseText ?? `(No license file shipped in the package; declared license: ${p.license}.)`;
  byText.set(t, [...(byText.get(t) ?? []), `${p.name}@${p.version}`]);
}
for (const [text, names] of byText) {
  out += `\n### ${names.join(", ")}\n\n\`\`\`\n${text}\n\`\`\`\n`;
}
fs.writeFileSync("THIRD_PARTY_NOTICES.md", out);
console.log(`Wrote THIRD_PARTY_NOTICES.md (${pkgs.length} packages).`);
